# Generated by Django 5.1.15 on 2026-09-26 11:10

import apps.business.ponds.models
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_core', '0002_seed_dashboards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('code', models.CharField(blank=True, help_text='e.g. P-1. Handy on small screens.', max_length=12, verbose_name='Short code')),
                ('location', models.CharField(blank=True, max_length=160, verbose_name='Location')),
                ('area', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Area')),
                ('area_decimal', models.DecimalField(blank=True, decimal_places=3, editable=False, max_digits=14, null=True)),
                ('depth_ft', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Water depth (feet)')),
                ('status', models.CharField(choices=[('in_use', 'Fish in it'), ('preparing', 'Being prepared'), ('empty', 'Empty / dry')], default='in_use', max_length=10, verbose_name='Status')),
                ('ownership', models.CharField(choices=[('own', 'Own'), ('leased', 'Leased')], default='own', max_length=8, verbose_name='Ownership')),
                ('lease_from', models.CharField(blank=True, max_length=120, verbose_name='Leased from')),
                ('lease_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Lease amount')),
                ('lease_start', models.DateField(blank=True, null=True, verbose_name='Lease starts')),
                ('lease_end', models.DateField(blank=True, null=True, verbose_name='Lease ends')),
                ('photo', models.FileField(blank=True, upload_to=apps.business.ponds.models.pond_photo_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'heic'])], verbose_name='Photo')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('area_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='business_core.unit', verbose_name='Area unit')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='business_core.business')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['business', 'is_deleted', 'status'], name='business_po_busines_13bf3f_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('business', 'name'), name='pond_name_unique_per_business')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
