# Generated by Django 5.1.15 on 2026-09-28 17:38

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_core', '0002_seed_dashboards'),
        ('business_ponds', '0002_culturecycle_harvest_mortality_sampleweighing_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PondAlerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oxygen_min', models.DecimalField(decimal_places=2, default=Decimal('4'), max_digits=5, verbose_name='Oxygen: warn below (mg/L)')),
                ('ph_min', models.DecimalField(decimal_places=2, default=Decimal('6.5'), max_digits=4, verbose_name='pH: warn below')),
                ('ph_max', models.DecimalField(decimal_places=2, default=Decimal('8.5'), max_digits=4, verbose_name='pH: warn above')),
                ('temperature_min', models.DecimalField(decimal_places=2, default=Decimal('20'), max_digits=5, verbose_name='Temperature: warn below (°C)')),
                ('temperature_max', models.DecimalField(decimal_places=2, default=Decimal('32'), max_digits=5, verbose_name='Temperature: warn above (°C)')),
                ('ammonia_max', models.DecimalField(decimal_places=2, default=Decimal('0.5'), max_digits=5, verbose_name='Ammonia: warn above (mg/L)')),
                ('transparency_min', models.DecimalField(decimal_places=1, default=Decimal('25'), max_digits=5, verbose_name='Transparency: warn below (cm)')),
                ('transparency_max', models.DecimalField(decimal_places=1, default=Decimal('40'), max_digits=5, verbose_name='Transparency: warn above (cm)')),
                ('deaths_pct', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Deaths: warn when more than this % of the fish die in 3 days')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pond_alerts', to='business_core.business')),
            ],
            options={
                'verbose_name': 'pond alert levels',
            },
        ),
        migrations.CreateModel(
            name='WaterTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('date', models.DateField(verbose_name='Date')),
                ('time_of_day', models.CharField(blank=True, choices=[('dawn', 'Early morning'), ('day', 'Daytime'), ('evening', 'Evening'), ('night', 'Night')], max_length=8, verbose_name='Time')),
                ('oxygen', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Dissolved oxygen (mg/L)')),
                ('ph', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='pH')),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Water temperature (°C)')),
                ('ammonia', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ammonia (mg/L)')),
                ('transparency', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Transparency (cm)')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='business_core.business')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_tests', to='business_ponds.culturecycle')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['cycle', 'is_deleted', 'date'], name='business_po_cycle_i_0e618e_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
