# Generated by Django 5.1.15 on 2026-10-05 14:02

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_core', '0003_membership_account_created'),
        ('business_finance', '0002_recurringtransaction_transaction_transfer_budget_and_more'),
        ('business_ponds', '0003_water_tests_and_alert_levels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('date', models.DateField(verbose_name='Date')),
                ('kind', models.CharField(choices=[('lime', 'Lime (chun)'), ('fertilizer', 'Fertilizer (urea, TSP, dung)'), ('salt', 'Salt'), ('potash', 'Potash'), ('medicine', 'Medicine / antibiotic'), ('probiotic', 'Probiotic / water care'), ('other', 'Other')], default='lime', max_length=12, verbose_name='What kind')),
                ('product', models.CharField(help_text='e.g. Dolomite lime, Oxytetracycline, Aquakleen', max_length=100, verbose_name='Product')),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amount used')),
                ('reason', models.CharField(blank=True, help_text='e.g. pond preparation, red spots on fish, low oxygen', max_length=160, verbose_name='Why')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cost')),
                ('withdrawal_days', models.PositiveSmallIntegerField(blank=True, help_text="The waiting period on the medicine's label. Leave empty if there is none.", null=True, verbose_name="Don't sell fish for (days)")),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='business_finance.account', verbose_name='Paid from')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='business_core.business')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='business_ponds.culturecycle')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='business_core.unit', verbose_name='Unit')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['cycle', 'is_deleted', 'date'], name='business_po_cycle_i_a7ddbe_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
