# Generated by Django 5.1.15 on 2026-10-07 13:40

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_core', '0003_membership_account_created'),
        ('business_ponds', '0006_treatment_store'),
        ('business_species', '0002_market_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FishMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('date', models.DateField(verbose_name='Date')),
                ('count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of fish')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total weight')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, editable=False, max_digits=14, null=True)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Their value')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='business_core.business')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves_out', to='business_ponds.culturecycle', verbose_name='From')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='business_species.species', verbose_name='Fish')),
                ('to_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves_in', to='business_ponds.culturecycle', verbose_name='To')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('weight_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='business_core.unit', verbose_name='Weight unit')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['cycle', 'is_deleted', 'date'], name='business_po_cycle_i_003cd0_idx'), models.Index(fields=['to_cycle', 'is_deleted', 'date'], name='business_po_to_cycl_a190bf_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
