# Generated by Django 5.1.15 on 2026-10-08 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_finance', '0003_familymember_transaction_member_and_more'),
        ('business_ponds', '0007_fish_move'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocking',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='business_finance.account', verbose_name='Paid from'),
        ),
    ]
