# Generated by Django 5.1.15 on 2026-10-07 13:49

import apps.business.papers.models
import apps.core.receipts
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_core', '0003_membership_account_created'),
        ('business_ponds', '0007_fish_move'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('title', models.CharField(help_text='e.g. Trade licence 2026–27', max_length=120, verbose_name='Name')),
                ('kind', models.CharField(choices=[('trade', 'Trade licence'), ('fishery', 'Fish farm registration'), ('lease', 'Pond lease agreement'), ('land', 'Land papers (dolil, khatian, porcha)'), ('tax', 'Tax, TIN or VAT'), ('bank', 'Bank or loan papers'), ('insurance', 'Insurance'), ('other', 'Other')], default='trade', max_length=10, verbose_name='What kind')),
                ('number', models.CharField(blank=True, help_text='Licence, registration or deed number.', max_length=60, verbose_name='Number')),
                ('issued_by', models.CharField(blank=True, help_text='e.g. Union Parishad, Upazila Fisheries Office', max_length=120, verbose_name='Issued by')),
                ('issued_on', models.DateField(blank=True, null=True, verbose_name='Issued on')),
                ('expires_on', models.DateField(blank=True, help_text='Leave empty if it never runs out.', null=True, verbose_name='Valid until')),
                ('remind_days', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MaxValueValidator(365)], verbose_name='Remind me (days before)')),
                ('file', models.FileField(blank=True, upload_to=apps.business.papers.models.paper_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'heic', 'pdf']), apps.core.receipts.max_size], verbose_name='Photo or PDF')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='business_core.business')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pond', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papers', to='business_ponds.pond', verbose_name='For pond')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': [models.OrderBy(models.F('expires_on'), nulls_last=True), 'title'],
                'indexes': [models.Index(fields=['business', 'is_deleted', 'expires_on'], name='business_pa_busines_8e761d_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
