# Generated by Django 5.1.15 on 2026-09-26 11:10

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_core', '0002_seed_dashboards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('brand', models.CharField(blank=True, max_length=80, verbose_name='Brand / company')),
                ('form', models.CharField(choices=[('floating', 'Floating'), ('sinking', 'Sinking'), ('powder', 'Powder / mash'), ('other', 'Other')], default='floating', max_length=10, verbose_name='Type')),
                ('stage', models.CharField(blank=True, choices=[('nursery', 'Nursery'), ('starter', 'Starter'), ('grower', 'Grower'), ('finisher', 'Finisher')], max_length=10, verbose_name='Stage')),
                ('protein_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Protein')),
                ('bag_size', models.DecimalField(decimal_places=3, default=25, max_digits=8, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Bag size')),
                ('default_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Usual price per bag')),
                ('low_stock_bags', models.DecimalField(blank=True, decimal_places=1, help_text='Low-stock alert once feed stock is tracked.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Warn me below (bags)')),
                ('bag_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='business_core.unit', verbose_name='Bag unit')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='business_core.business')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['brand', 'name'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
