# Generated by Django 5.1.15 on 2026-09-26 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_feed', '0001_initial'),
        ('business_parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedproduct',
            name='suppliers',
            field=models.ManyToManyField(blank=True, related_name='feed_products', to='business_parties.party', verbose_name='Bought from'),
        ),
        migrations.AddField(
            model_name='feedproduct',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='feedproduct',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('business', 'name'), name='feed_name_unique_per_business'),
        ),
    ]
