# Generated by Django 5.1.15 on 2026-09-26 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_core', '0002_seed_dashboards'),
        ('business_feed', '0003_feedpurchase_feedpurchaseline_feedusage'),
        ('business_ponds', '0002_culturecycle_harvest_mortality_sampleweighing_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedusage',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedings', to='business_ponds.culturecycle', verbose_name='Pond'),
        ),
        migrations.AddField(
            model_name='feedusage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='business_feed.feedproduct', verbose_name='Feed'),
        ),
        migrations.AddField(
            model_name='feedusage',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='business_core.unit', verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='feedusage',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='feedpurchase',
            index=models.Index(fields=['business', 'is_deleted', 'date'], name='business_fe_busines_3b0c7e_idx'),
        ),
        migrations.AddIndex(
            model_name='feedpurchase',
            index=models.Index(fields=['supplier', 'date'], name='business_fe_supplie_846e2b_idx'),
        ),
        migrations.AddIndex(
            model_name='feedusage',
            index=models.Index(fields=['business', 'is_deleted', 'date'], name='business_fe_busines_f41c89_idx'),
        ),
        migrations.AddIndex(
            model_name='feedusage',
            index=models.Index(fields=['cycle', 'is_deleted', 'date'], name='business_fe_cycle_i_6fe81c_idx'),
        ),
    ]
