# Generated by Django 5.1.15 on 2026-09-26 11:10

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_core', '0002_seed_dashboards'),
        ('business_markets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Phone')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Address')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Contact person')),
                ('is_supplier', models.BooleanField(default=False, help_text='Sells you feed, fingerlings, medicine…', verbose_name='Supplier')),
                ('is_buyer', models.BooleanField(default=False, help_text='Buys your fish.', verbose_name='Buyer')),
                ('buyer_type', models.CharField(blank=True, choices=[('aratdar', 'Aratdar / wholesaler'), ('paikar', 'Paikar / trader'), ('retail', 'Retail / local buyer'), ('other', 'Other')], max_length=10, verbose_name='Buyer type')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Balance before using this app')),
                ('opening_type', models.CharField(choices=[('receivable', 'They owe me'), ('payable', 'I owe them')], default='payable', max_length=10, verbose_name='Who owes whom')),
                ('opening_date', models.DateField(blank=True, null=True, verbose_name='As of')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='business_core.business')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyers', to='business_markets.market', verbose_name='Usual market')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'parties',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['business', 'is_deleted', 'is_supplier'], name='business_pa_busines_e7c62c_idx'), models.Index(fields=['business', 'is_deleted', 'is_buyer'], name='business_pa_busines_3787c8_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('business', 'name'), name='party_name_unique_per_business')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
