# Generated by Django 5.1.15 on 2026-09-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_parties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='follow_up_note',
            field=models.CharField(blank=True, max_length=160, verbose_name='Promise / note'),
        ),
        migrations.AddField(
            model_name='party',
            name='follow_up_on',
            field=models.DateField(blank=True, help_text='A date they promised to pay, or to remind them.', null=True, verbose_name='Follow up on'),
        ),
    ]
