# Generated by Django 5.1.15 on 2026-09-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='background',
            field=models.CharField(choices=[('paper', 'Warm Paper'), ('white', 'Clean White'), ('notepad', 'Notepad Yellow'), ('honeydew', 'Honeydew Green'), ('sky', 'Sky Mist'), ('blush', 'Rose Blush'), ('lavender', 'Lavender')], default='paper', max_length=10),
        ),
    ]
