# Generated by Django 5.1.15 on 2026-10-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='view_mode',
            field=models.CharField(choices=[('auto', 'Automatic'), ('app', 'App view'), ('web', 'Website view')], default='auto', max_length=5),
        ),
    ]
