# Generated by Django 5.1.15 on 2026-10-05 17:18

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_core', '0003_membership_account_created'),
        ('business_finance', '0002_recurringtransaction_transaction_transfer_budget_and_more'),
        ('business_parties', '0002_party_follow_up_note_party_follow_up_on'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(help_text='e.g. Dolomite lime, Urea, Oxytetracycline', max_length=100, verbose_name='Name')),
                ('kind', models.CharField(choices=[('lime', 'Lime (chun)'), ('fertilizer', 'Fertilizer (urea, TSP, dung)'), ('salt', 'Salt'), ('potash', 'Potash'), ('medicine', 'Medicine / antibiotic'), ('probiotic', 'Probiotic / water care'), ('other', 'Other')], default='lime', max_length=12, verbose_name='What kind')),
                ('low_stock', models.DecimalField(blank=True, decimal_places=3, help_text='In the unit above. Leave empty for no warning.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Warn me below')),
                ('dose_per_decimal', models.DecimalField(blank=True, decimal_places=3, help_text='Optional, from the bag or bottle, e.g. 1 kg lime per decimal. Fills the dose when you use it.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Usual dose per decimal')),
                ('withdrawal_days', models.PositiveSmallIntegerField(blank=True, help_text="A medicine's waiting period, filled in each time you use it.", null=True, verbose_name="Don't sell fish for (days)")),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='business_core.business')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(help_text='The unit the stock is shown in: kg for lime, litre or bottle for medicine.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='business_core.unit', verbose_name='Counted in')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SupplyPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('date', models.DateField(verbose_name='Date')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Quantity')),
                ('base_quantity', models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=18)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total price')),
                ('paid_now', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Paid now')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='business_finance.account', verbose_name='Paid from')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='business_core.business')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='business_supplies.supplyitem')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='business_parties.party', verbose_name='Bought from')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='business_core.unit', verbose_name='Unit')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='supplyitem',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('business', 'name'), name='supply_item_name_unique_per_business'),
        ),
        migrations.AddIndex(
            model_name='supplypurchase',
            index=models.Index(fields=['business', 'is_deleted', 'date'], name='business_su_busines_10d341_idx'),
        ),
    ]
