# Generated by Django 5.1.15 on 2026-09-26 14:18

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_core', '0002_seed_dashboards'),
        ('business_feed', '0004_feedusage_cycle_feedusage_product_feedusage_unit_and_more'),
        ('business_finance', '0001_initial'),
        ('business_parties', '0002_party_follow_up_note_party_follow_up_on'),
        ('business_ponds', '0002_culturecycle_harvest_mortality_sampleweighing_and_more'),
        ('business_sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('direction', models.CharField(choices=[('in', 'Received from them'), ('out', 'Paid to them')], default='in', max_length=3, verbose_name='Money')),
                ('date', models.DateField(db_index=True, verbose_name='Date')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amount')),
                ('discount', models.DecimalField(decimal_places=2, default=0, help_text='Settled without money changing hands, e.g. ৳50 let go to round off.', max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Discount / let go')),
                ('reference', models.CharField(blank=True, max_length=60, verbose_name='Receipt / reference')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='business_finance.account', verbose_name='Account')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='business_core.business')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('feed_purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='later_payments', to='business_feed.feedpurchase')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='business_parties.party', verbose_name='Who')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='later_payments', to='business_sales.fishsale')),
                ('stocking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='later_payments', to='business_ponds.stocking')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['business', 'is_deleted', 'date'], name='business_cr_busines_37c72e_idx'), models.Index(fields=['party', 'date'], name='business_cr_party_i_cb7345_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
