# Generated by Django 5.1.15 on 2026-10-05 14:19

import datetime
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_core', '0003_membership_account_created'),
        ('business_finance', '0002_recurringtransaction_transaction_transfer_budget_and_more'),
        ('business_ponds', '0004_treatment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('job', models.CharField(blank=True, help_text='e.g. guard, feeder, manager, net puller', max_length=60, verbose_name='Work')),
                ('pay_type', models.CharField(choices=[('monthly', 'Monthly salary'), ('daily', 'Daily wage')], default='monthly', max_length=8, verbose_name='Paid by')),
                ('rate', models.DecimalField(decimal_places=2, help_text='Per month for a monthly salary, per day for a daily wage.', max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Salary or wage')),
                ('started_on', models.DateField(default=datetime.date.today, verbose_name='Started on')),
                ('left_on', models.DateField(blank=True, help_text='Leave empty while they still work here.', null=True, verbose_name='Left on')),
                ('address', models.CharField(blank=True, max_length=160, verbose_name='Address')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, help_text='Wages you already owed them (+), or an advance they already had (−). Usually 0.', max_digits=14, verbose_name='Balance when you start')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='business_core.business')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('date', models.DateField(verbose_name='Date')),
                ('kind', models.CharField(choices=[('work', 'Days worked'), ('salary', 'Monthly salary'), ('bonus', 'Bonus / extra'), ('deduction', 'Deduction / fine')], default='work', max_length=10, verbose_name='What for')),
                ('days', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Days')),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Rate')),
                ('month', models.DateField(blank=True, editable=False, null=True, verbose_name='Month')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amount')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='business_core.business')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(blank=True, help_text="Optional: work done for one pond counts towards that pond's cost.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_earnings', to='business_ponds.culturecycle', verbose_name='Pond')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='business_staff.worker')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='WorkerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('date', models.DateField(verbose_name='Date')),
                ('kind', models.CharField(choices=[('wage', 'Wages / salary'), ('advance', 'Advance')], default='wage', max_length=8, verbose_name='What for')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='business_finance.account', verbose_name='Paid from')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='business_core.business')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='business_staff.worker')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='worker',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('business', 'name'), name='worker_name_unique_per_business'),
        ),
        migrations.AddIndex(
            model_name='earning',
            index=models.Index(fields=['business', 'is_deleted', 'date'], name='business_st_busines_8843e8_idx'),
        ),
        migrations.AddConstraint(
            model_name='earning',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('kind', 'salary')), fields=('worker', 'month'), name='one_salary_per_worker_month'),
        ),
        migrations.AddIndex(
            model_name='workerpayment',
            index=models.Index(fields=['business', 'is_deleted', 'date'], name='business_st_busines_4bf78c_idx'),
        ),
    ]
