# Generated by Django 5.1.15 on 2026-09-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_core', '0002_seed_dashboards'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='account_created',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
