# Generated by Django 5.1.15 on 2026-10-05 19:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZakatSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basis', models.CharField(choices=[('silver', 'Silver (52.5 tola) — the lower, safer line'), ('gold', 'Gold (7.5 tola)')], default='silver', max_length=6, verbose_name='Nisab by')),
                ('gold_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Gold price per gram')),
                ('silver_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Silver price per gram')),
                ('gold_grams', models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Gold you own (grams)')),
                ('silver_grams', models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Silver you own (grams)')),
                ('other_assets', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Other savings & investments')),
                ('other_debts', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Other debts due now')),
                ('farm_share', models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Your share of the farm (%)')),
                ('skip', models.JSONField(blank=True, default=list, help_text='Keys of the automatic lines left out.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zakat_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
