# Generated by Django 5.1.15 on 2026-08-05 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('GROCERY', 'Grocery'), ('PHARMACY', 'Pharmacy'), ('VEGETABLE', 'Vegetable & Fruit'), ('BAKERY', 'Bakery'), ('HARDWARE', 'Hardware Store'), ('CLOTHING', 'Clothing'), ('ELECTRONICS', 'Electronics'), ('STATIONERY', 'Stationery'), ('RESTAURANT', 'Restaurant'), ('OTHER', 'Other')], default='OTHER', max_length=32)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('PURCHASE', 'Purchase (বাকি)'), ('PAYMENT', 'Payment')], default='PURCHASE', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='shops.shop')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
