# Generated by Django 5.1.15 on 2026-08-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='due_date',
            field=models.DateField(blank=True, help_text='Next settlement due date (optional).', null=True),
        ),
    ]
