# Generated by Django 5.1.15 on 2026-10-05 19:28

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creditors', '0009_field_labels'),
        ('debtors', '0006_field_labels'),
        ('shops', '0005_field_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Each installment')),
                ('frequency', models.CharField(choices=[('weekly', 'Every week'), ('biweekly', 'Every 2 weeks'), ('monthly', 'Every month')], default='monthly', max_length=10, verbose_name='How often')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='First installment on')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creditor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='creditors.creditor')),
                ('debtor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='debtors.debtor')),
                ('shop', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='shops.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('creditor__isnull', False), ('debtor__isnull', True), ('shop__isnull', True)), models.Q(('creditor__isnull', True), ('debtor__isnull', False), ('shop__isnull', True)), models.Q(('creditor__isnull', True), ('debtor__isnull', True), ('shop__isnull', False)), _connector='OR'), name='plan_for_exactly_one_ledger')],
            },
        ),
    ]
