# Generated by Django 5.1.15 on 2026-04-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("debtors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="debtor",
            name="category",
            field=models.CharField(
                choices=[
                    ("FAMILY", "Family"),
                    ("FRIEND", "Friend"),
                    ("BUSINESS_PARTNER", "Business Partner"),
                    ("CLIENT", "Client"),
                    ("EMPLOYEE", "Employee"),
                    ("TENANT", "Tenant"),
                    ("SHOPKEEPER", "Shopkeeper"),
                    ("SUPPLIER", "Supplier"),
                    ("STUDENT", "Student"),
                    ("MEDICAL", "Medical"),
                    ("EDUCATION", "Education"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=32,
            ),
        ),
    ]
