# Generated by Django 5.1.15 on 2026-08-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtors', '0002_debtor_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtor',
            name='due_date',
            field=models.DateField(blank=True, help_text='Next expected repayment date (optional).', null=True),
        ),
    ]
