# Generated by Django 5.1.15 on 2026-10-05 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtors', '0005_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='category',
            field=models.CharField(choices=[('FAMILY', 'Family'), ('FRIEND', 'Friend'), ('BUSINESS_PARTNER', 'Business Partner'), ('CLIENT', 'Client'), ('EMPLOYEE', 'Employee'), ('TENANT', 'Tenant'), ('SHOPKEEPER', 'Shopkeeper'), ('SUPPLIER', 'Supplier'), ('STUDENT', 'Student'), ('MEDICAL', 'Medical'), ('EDUCATION', 'Education'), ('OTHER', 'Other')], default='OTHER', max_length=32, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='due_date',
            field=models.DateField(blank=True, help_text='Next expected repayment date (optional).', null=True, verbose_name='Due date'),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive records are hidden from lists and pickers but still count in totals.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='debtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='debtors.debtor', verbose_name='Debtor'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('LEND', 'Lent'), ('RECEIVE', 'Received')], default='LEND', max_length=10, verbose_name='Type'),
        ),
    ]
