# Generated by Django 5.1.15 on 2026-04-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contributor",
            name="category",
            field=models.CharField(
                choices=[
                    ("FAMILY", "Family"),
                    ("FRIEND", "Friend"),
                    ("BUSINESS_PARTNER", "Business Partner"),
                    ("ORGANIZATION", "Organization"),
                    ("NGO", "NGO"),
                    ("SPONSOR", "Sponsor"),
                    ("DONOR", "Donor"),
                    ("INVESTOR", "Investor"),
                    ("ALUMNI", "Alumni"),
                    ("COMMUNITY", "Community"),
                    ("RELATIVE", "Relative"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=32,
            ),
        ),
    ]
