# Generated by Django 5.1.15 on 2026-10-05 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0004_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='contributors.contributor', verbose_name='Contributor'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='category',
            field=models.CharField(choices=[('FAMILY', 'Family'), ('FRIEND', 'Friend'), ('BUSINESS_PARTNER', 'Business Partner'), ('ORGANIZATION', 'Organization'), ('NGO', 'NGO'), ('SPONSOR', 'Sponsor'), ('DONOR', 'Donor'), ('INVESTOR', 'Investor'), ('ALUMNI', 'Alumni'), ('COMMUNITY', 'Community'), ('RELATIVE', 'Relative'), ('OTHER', 'Other')], default='OTHER', max_length=32, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive records are hidden from lists and pickers but still count in totals.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone'),
        ),
    ]
