# Generated by Django 5.1.15 on 2026-10-05 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='What')),
                ('kind', models.CharField(max_length=80, verbose_name='Kind')),
                ('data', models.TextField(help_text='The deleted rows as Django JSON, the ones others depend on first.')),
                ('relinks', models.JSONField(blank=True, default=list, help_text='Rows that pointed at the deleted ones and were set to empty: [model, field, [[pk, value], …]].')),
                ('count', models.PositiveIntegerField(default=1)),
                ('back_url', models.CharField(blank=True, max_length=300)),
                ('deleted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-deleted_at', '-id'],
            },
        ),
    ]
