# Generated by Django 5.1.15 on 2026-09-26 10:29

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_core', '0002_seed_dashboards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('kind', models.CharField(choices=[('bank', 'Bank'), ('ngo', 'NGO / microfinance'), ('samity', 'Samity / co-operative'), ('person', 'Person'), ('other', 'Other')], default='bank', max_length=10, verbose_name='Type')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Phone')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Branch / address')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='business_core.business')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='Purpose')),
                ('account_no', models.CharField(blank=True, max_length=60, verbose_name='Loan / account number')),
                ('principal', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('1'))], verbose_name='Amount borrowed')),
                ('taken_on', models.DateField(verbose_name='Date received')),
                ('rate', models.DecimalField(decimal_places=4, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Interest rate')),
                ('rate_period', models.CharField(choices=[('year', 'per year'), ('month', 'per month')], default='year', max_length=5, verbose_name='Rate is')),
                ('method', models.CharField(choices=[('reducing', "On what's still owed"), ('flat', 'On the full amount (flat)')], default='reducing', max_length=10, verbose_name='Interest is charged')),
                ('every', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='Pay every')),
                ('every_unit', models.CharField(choices=[('month', 'months'), ('week', 'weeks')], default='month', max_length=5)),
                ('repayment', models.CharField(choices=[('end', 'All at the end'), ('equal', 'A part every time'), ('emi', 'Equal instalments (EMI)')], default='end', max_length=5, verbose_name='Loan amount is paid back')),
                ('first_due', models.DateField(blank=True, null=True, verbose_name='First payment date')),
                ('maturity', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('closed_on', models.DateField(blank=True, null=True, verbose_name='Closed on')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='business_core.business')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='business_loans.lender', verbose_name='Lender')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['closed_on', '-taken_on'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='LoanRateChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('effective_from', models.DateField(verbose_name='From')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='New rate')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='business_core.business')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_changes', to='business_loans.loan')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['effective_from'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='LoanTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('kind', models.CharField(choices=[('payment', 'Payment'), ('top_up', 'Extra borrowing')], default='payment', max_length=8)),
                ('date', models.DateField(verbose_name='Date')),
                ('principal', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Towards the loan')),
                ('interest', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Interest')),
                ('charges', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Fees / fines')),
                ('paid_via', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank transfer'), ('mobile', 'bKash / Nagad'), ('cheque', 'Cheque'), ('other', 'Other')], default='cash', max_length=8, verbose_name='Paid by')),
                ('reference', models.CharField(blank=True, max_length=60, verbose_name='Receipt / reference')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='business_core.business')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='business_loans.loan')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='lender',
            index=models.Index(fields=['business', 'is_deleted', 'name'], name='business_lo_busines_ac2eb2_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['business', 'is_deleted', 'closed_on'], name='business_lo_busines_302ffb_idx'),
        ),
        migrations.AddConstraint(
            model_name='loanratechange',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('loan', 'effective_from'), name='one_rate_change_per_day'),
        ),
        migrations.AddIndex(
            model_name='loantransaction',
            index=models.Index(fields=['loan', 'is_deleted', 'date'], name='business_lo_loan_id_f69538_idx'),
        ),
        migrations.AddIndex(
            model_name='loantransaction',
            index=models.Index(fields=['business', 'date'], name='business_lo_busines_483a54_idx'),
        ),
    ]
