# Generated by Django 5.1.15 on 2026-09-28 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_finance', '0002_recurringtransaction_transaction_transfer_budget_and_more'),
        ('business_loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loantransaction',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='business_finance.account', verbose_name='Account'),
        ),
    ]
