# Generated by Django 5.1.15 on 2026-10-08 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_finance', '0003_familymember_transaction_member_and_more'),
        ('business_loans', '0002_loantransaction_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='business_finance.account', verbose_name='Received into'),
        ),
        migrations.AlterField(
            model_name='lender',
            name='kind',
            field=models.CharField(choices=[('bank', 'Bank'), ('ngo', 'NGO / microfinance'), ('samity', 'Samity / co-operative'), ('person', 'Person'), ('family', 'Relative / family'), ('other', 'Other')], default='bank', max_length=10, verbose_name='Type'),
        ),
    ]
