# Generated by Django 5.1.15 on 2026-10-05 19:00

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('kind', models.CharField(choices=[('cash', 'Cash in hand'), ('bank', 'Bank account'), ('mobile', 'Mobile banking (bKash, Nagad…)'), ('other', 'Other')], default='cash', max_length=8, verbose_name='Type')),
                ('number', models.CharField(blank=True, max_length=40, verbose_name='Account / wallet number')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Balance when you start')),
                ('opening_date', models.DateField(default=datetime.date.today, verbose_name='As of')),
                ('is_default', models.BooleanField(default=False, help_text='Picked first when you record money in or out.', verbose_name='Use by default')),
                ('is_active', models.BooleanField(default=True, verbose_name='In use')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('fee', models.DecimalField(decimal_places=2, default=0, help_text='e.g. the bKash cash-out charge. It comes out of the “From” wallet.', max_digits=12, verbose_name='Fee / charge')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transfers', to=settings.AUTH_USER_MODEL)),
                ('from_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='wallets.wallet', verbose_name='From')),
                ('to_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='wallets.wallet', verbose_name='To')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Signed: + adds to the balance, − takes away.', max_digits=12, verbose_name='Amount')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='wallets.wallet')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='wallet_name_unique_per_user'),
        ),
    ]
