# Generated by Django 5.1.15 on 2026-09-25 18:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expense', '0004_expensecategory_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('expenses', 'All expenses'), ('category', 'One expense category'), ('bazar', 'Household bazar')], default='category', max_length=10, verbose_name='Budget for')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Monthly limit')),
                ('alert_at', models.PositiveSmallIntegerField(default=80, help_text="Percent of the limit. You'll also be warned if the current pace would overshoot it.", validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)], verbose_name='Warn me at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='expense.expensecategory', verbose_name='Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scope', 'category__name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('scope', 'category')), fields=('user', 'category'), name='one_budget_per_category'), models.UniqueConstraint(condition=models.Q(('scope', 'category'), _negated=True), fields=('user', 'scope'), name='one_budget_per_scope')],
            },
        ),
    ]
