# Generated by Django 5.1.15 on 2026-09-29 13:08

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_core', '0002_seed_dashboards'),
        ('business_ponds', '0003_water_tests_and_alert_levels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=150, verbose_name='What')),
                ('date', models.DateField(verbose_name='Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Until')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Time')),
                ('category', models.CharField(choices=[('work', 'Farm work'), ('task', 'To do'), ('money', 'Money'), ('festival', 'Holiday / festival'), ('personal', 'Personal')], default='work', max_length=10, verbose_name='Kind')),
                ('repeat', models.CharField(blank=True, choices=[('', "Doesn't repeat"), ('weekly', 'Every week'), ('monthly', 'Every month (English date)'), ('bn_monthly', 'Every month (Bangla date)'), ('yearly', 'Every year (English date)'), ('bn_yearly', 'Every year (Bangla date)')], default='', max_length=10, verbose_name='Repeat')),
                ('repeat_until', models.DateField(blank=True, null=True, verbose_name='Repeat until')),
                ('done', models.BooleanField(default=False, verbose_name='Done')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='business_core.business')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pond', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='business_ponds.pond', verbose_name='Pond')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'time', 'id'],
                'indexes': [models.Index(fields=['business', 'is_deleted', 'date'], name='business_ca_busines_caa89a_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
