# Generated by Django 5.1.15 on 2026-08-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditors', '0002_creditor_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditor',
            name='due_date',
            field=models.DateField(blank=True, help_text='Next payment due date (optional).', null=True),
        ),
    ]
