# Generated by Django 5.1.15 on 2026-08-07 08:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditors', '0003_creditor_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditor',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual simple interest rate, %% (optional). Leave blank for interest-free debt.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
