# Generated by Django 5.1.15 on 2026-08-07 10:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditors', '0005_creditor_interest_fixed_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditor',
            name='interest_basis',
            field=models.CharField(blank=True, choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed Amount')], help_text='For Monthly/Every 3 Months/Every 6 Months/Yearly: charge a percentage of the balance, or a flat amount each period.', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='creditor',
            name='interest_fixed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='A flat interest amount (৳) — used for a one-time Fixed Amount type, or a Fixed Amount basis charged every period.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='creditor',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Interest rate per period, %% — used when the basis is Percentage.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='creditor',
            name='interest_type',
            field=models.CharField(blank=True, choices=[('FIXED', 'Fixed Amount (One-Time)'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Every 3 Months'), ('SEMI_ANNUAL', 'Every 6 Months'), ('YEARLY', 'Yearly')], help_text='How interest is charged (optional). Leave blank for interest-free debt.', max_length=16, null=True),
        ),
    ]
