# Generated by Django 5.1.15 on 2026-10-05 19:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditors', '0008_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditor',
            name='category',
            field=models.CharField(choices=[('FAMILY', 'Family'), ('FRIEND', 'Friend'), ('BUSINESS_PARTNER', 'Business Partner'), ('BANK', 'Bank'), ('MICROFINANCE', 'Microfinance'), ('MONEYLENDER', 'Moneylender'), ('SUPPLIER', 'Supplier'), ('LANDLORD', 'Landlord'), ('UTILITY', 'Utility'), ('MEDICAL', 'Medical'), ('EDUCATION', 'Education'), ('OTHER', 'Other')], default='OTHER', max_length=32, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='creditor',
            name='due_date',
            field=models.DateField(blank=True, help_text='Next payment due date (optional).', null=True, verbose_name='Due date'),
        ),
        migrations.AlterField(
            model_name='creditor',
            name='interest_basis',
            field=models.CharField(blank=True, choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed Amount')], help_text='For Monthly/Every 3 Months/Every 6 Months/Yearly: charge a percentage of the balance, or a flat amount each period.', max_length=16, null=True, verbose_name='Interest basis'),
        ),
        migrations.AlterField(
            model_name='creditor',
            name='interest_fixed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='A flat interest amount (৳) — used for a one-time Fixed Amount type, or a Fixed Amount basis charged every period.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Fixed interest amount'),
        ),
        migrations.AlterField(
            model_name='creditor',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Interest rate per period, %% — used when the basis is Percentage.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Interest rate'),
        ),
        migrations.AlterField(
            model_name='creditor',
            name='interest_type',
            field=models.CharField(blank=True, choices=[('FIXED', 'Fixed Amount (One-Time)'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Every 3 Months'), ('SEMI_ANNUAL', 'Every 6 Months'), ('YEARLY', 'Yearly')], help_text='How interest is charged (optional). Leave blank for interest-free debt.', max_length=16, null=True, verbose_name='Interest type'),
        ),
        migrations.AlterField(
            model_name='creditor',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive records are hidden from lists and pickers but still count in totals.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='creditor',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='creditor',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='creditor',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='creditor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='creditors.creditor', verbose_name='Creditor'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('BORROW', 'Borrowed'), ('REPAY', 'Repaid')], default='BORROW', max_length=10, verbose_name='Type'),
        ),
    ]
