# Generated by Django 5.1.15 on 2026-10-05 17:13

from django.db import migrations, models

# Copied (not imported) so the migration never changes when the seed list does.
SIZES = {
    "rui": 1000, "katla": 1500, "mrigal": 800, "kalibaus": 800, "silver carp": 1000, "grass carp": 1500,
    "common carp": 1000, "bighead carp": 1500, "pangas": 1000, "tilapia": 250, "koi": 100, "shing": 60,
    "magur": 150, "pabda": 40, "gulsha": 40, "sarpunti": 200, "golda prawn": 60, "bagda shrimp": 40,
}


def fill_sizes(apps, schema_editor):
    Species = apps.get_model("business_species", "Species")
    for sp in Species.objects.filter(market_size_g__isnull=True):
        size = SIZES.get(sp.name.strip().lower())
        if size:
            sp.market_size_g = size
            sp.save(update_fields=["market_size_g"])


class Migration(migrations.Migration):

    dependencies = [
        ('business_species', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='market_size_g',
            field=models.PositiveIntegerField(blank=True, help_text='The size you usually sell this fish at, e.g. 1000 for 1 kg Rui. Used to guess when the fish in a pond will be ready.', null=True, verbose_name='Selling size (grams per fish)'),
        ),
        migrations.RunPython(fill_sizes, migrations.RunPython.noop),
    ]
