# Generated by Django 5.1.15 on 2026-10-07 15:19

from django.db import migrations, models

# The seeded fish get the usual stocking guide (apps/business/species/seed.py, kept as it was here).
GUIDE = {
    "Rui": 10, "Katla": 4, "Mrigal": 8, "Kalibaus": 3, "Silver carp": 6, "Grass carp": 3, "Common carp": 4, "Bighead carp": 2,
    "Pangas": 120, "Tilapia": 150, "Koi": 400, "Shing": 400, "Magur": 200, "Pabda": 250, "Gulsha": 300, "Sarpunti": 60,
    "Golda prawn": 40, "Bagda shrimp": 60,
}


def fill(apps, schema_editor):
    Species = apps.get_model("business_species", "Species")
    for name, n in GUIDE.items():
        Species.objects.filter(name__iexact=name, stock_per_decimal__isnull=True).update(stock_per_decimal=n)


class Migration(migrations.Migration):

    dependencies = [
        ('business_species', '0002_market_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='stock_per_decimal',
            field=models.PositiveIntegerField(blank=True, help_text='How many of this fish farmers usually release in one decimal of water. Carps are counted as their share of a mixed pond. Used to suggest how many to buy and to warn when a pond is too crowded.', null=True, verbose_name='Usual fingerlings per decimal'),
        ),
        migrations.RunPython(fill, migrations.RunPython.noop),
    ]
