# Generated by Django 5.1.15 on 2026-08-07 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frequency', models.CharField(choices=[('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Every 2 Weeks'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Every 3 Months'), ('YEARLY', 'Yearly')], max_length=10)),
                ('next_run_date', models.DateField()),
                ('note', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_incomes', to='income.incomesource')),
            ],
            options={
                'ordering': ['next_run_date'],
            },
        ),
        migrations.AddField(
            model_name='incometransaction',
            name='recurring_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='income.recurringincome'),
        ),
    ]
