# Generated by Django 5.1.15 on 2026-10-05 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0005_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomesource',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='incomesource',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive records are hidden from lists and pickers but still count in totals.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='incomesource',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='incometransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='incometransaction',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='incometransaction',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='incometransaction',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='income.incomesource', verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='recurringincome',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='recurringincome',
            name='frequency',
            field=models.CharField(choices=[('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Every 2 Weeks'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Every 3 Months'), ('YEARLY', 'Yearly')], max_length=10, verbose_name='How often'),
        ),
        migrations.AlterField(
            model_name='recurringincome',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='recurringincome',
            name='next_run_date',
            field=models.DateField(verbose_name='Next date'),
        ),
        migrations.AlterField(
            model_name='recurringincome',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='recurringincome',
            name='skip_weekend',
            field=models.BooleanField(default=False, verbose_name='Skip weekends'),
        ),
        migrations.AlterField(
            model_name='recurringincome',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_incomes', to='income.incomesource', verbose_name='Source'),
        ),
    ]
