# Generated by Django 5.1.15 on 2026-10-07 12:41

from django.db import migrations, models


def fill_start(apps, schema_editor):
    """Existing schedules started on their first entry (or, with none yet, on the next date)."""
    from django.db.models import Min

    Schedule = apps.get_model("income", "RecurringIncome")
    Entry = apps.get_model("income", "IncomeTransaction")
    first = dict(Entry.objects.filter(recurring_source_id__isnull=False).values_list("recurring_source_id").annotate(d=Min("date")))
    for sch in Schedule.objects.filter(start_date__isnull=True):
        sch.start_date = first.get(sch.pk) or sch.next_run_date
        sch.save(update_fields=["start_date"])


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0006_field_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringincome',
            name='end_date',
            field=models.DateField(blank=True, help_text='Leave empty if it goes on. Nothing is created after this date.', null=True, verbose_name='Ends on'),
        ),
        migrations.AddField(
            model_name='recurringincome',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Starts on'),
        ),
        migrations.RunPython(fill_start, migrations.RunPython.noop),
    ]
