# Generated by Django 5.1.15 on 2026-09-25 18:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Goal')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Target amount')),
                ('target_date', models.DateField(blank=True, help_text="Optional. With a date you'll see how much to save each month to make it.", null=True, verbose_name='Target date')),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('orange', 'Orange'), ('green', 'Green'), ('gold', 'Gold'), ('pink', 'Pink'), ('teal', 'Teal')], default='blue', max_length=10, verbose_name='Colour')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('is_active', models.BooleanField(default=True, help_text='Archived goals are hidden from the main list; their history is kept.')),
                ('reached_at', models.DateField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['target_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GoalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('DEPOSIT', 'Add money'), ('WITHDRAW', 'Take out')], default='DEPOSIT', max_length=10, verbose_name='Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Amount')),
                ('date', models.DateField(verbose_name='Date')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='goals.savingsgoal')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
