# Generated by Django 5.1.15 on 2026-09-25 19:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalentry',
            name='is_auto',
            field=models.BooleanField(default=False, editable=False, help_text="Created by the goal's auto-save schedule."),
        ),
        migrations.CreateModel(
            name='AutoSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Amount each time')),
                ('frequency', models.CharField(choices=[('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Every 2 Weeks'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Every 3 Months'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=10, verbose_name='How often')),
                ('next_run_date', models.DateField(verbose_name='Next deposit on')),
                ('skip_weekend', models.BooleanField(default=False, verbose_name='Move to the previous working day if it falls on a Friday or Saturday')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='autosave', to='goals.savingsgoal')),
            ],
        ),
    ]
