# Generated by Django 5.1.15 on 2026-10-05 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_autosave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autosave',
            name='goal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='autosave', to='goals.savingsgoal', verbose_name='Goal'),
        ),
        migrations.AlterField(
            model_name='autosave',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='goalentry',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='goals.savingsgoal', verbose_name='Goal'),
        ),
        migrations.AlterField(
            model_name='savingsgoal',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Archived goals are hidden from the main list; their history is kept.', verbose_name='Active'),
        ),
    ]
