# Generated by Django 5.1.15 on 2026-10-07 12:41

from django.db import migrations, models


def fill_start(apps, schema_editor):
    """Existing auto-saves started on their first automatic deposit (or, with none yet, on the next date)."""
    from django.db.models import Min

    AutoSave = apps.get_model("goals", "AutoSave")
    Entry = apps.get_model("goals", "GoalEntry")
    first = dict(Entry.objects.filter(is_auto=True).values_list("goal_id").annotate(d=Min("date")))
    for sch in AutoSave.objects.filter(start_date__isnull=True):
        sch.start_date = first.get(sch.goal_id) or sch.next_run_date
        sch.save(update_fields=["start_date"])


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_field_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='autosave',
            name='end_date',
            field=models.DateField(blank=True, help_text='Leave empty if it goes on. Nothing is created after this date.', null=True, verbose_name='Ends on'),
        ),
        migrations.AddField(
            model_name='autosave',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Starts on'),
        ),
        migrations.RunPython(fill_start, migrations.RunPython.noop),
    ]
