# Generated by Django 5.1.15 on 2026-08-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_recurringexpense_expense_recurring_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringexpense',
            name='skip_weekend',
            field=models.BooleanField(default=False),
        ),
    ]
