# Generated by Django 5.1.15 on 2026-09-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_recurringexpense_skip_weekend'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive records are hidden from lists and pickers but still count in totals.'),
        ),
    ]
