# Generated by Django 5.1.15 on 2026-10-05 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='expense.expensecategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive records are hidden from lists and pickers but still count in totals.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_expenses', to='expense.expensecategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='frequency',
            field=models.CharField(choices=[('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Every 2 Weeks'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Every 3 Months'), ('YEARLY', 'Yearly')], max_length=10, verbose_name='How often'),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='next_run_date',
            field=models.DateField(verbose_name='Next date'),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='skip_weekend',
            field=models.BooleanField(default=False, verbose_name='Skip weekends'),
        ),
    ]
