# Generated by Django 5.1.15 on 2026-10-05 19:32

import apps.core.receipts
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0006_field_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='receipt',
            field=models.FileField(blank=True, help_text='Optional: a photo of the memo or receipt.', upload_to=apps.core.receipts.personal_receipt_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'heic', 'pdf']), apps.core.receipts.max_size], verbose_name='Receipt photo'),
        ),
    ]
