# Generated by Django 5.1.15 on 2026-10-05 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0002_householdcategory_is_active_and_more'),
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wallets.wallet', verbose_name='Wallet'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wallets.wallet', verbose_name='Wallet'),
        ),
    ]
