# Generated by Django 5.1.15 on 2026-10-05 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0003_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='householdcategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive records are hidden from lists and pickers but still count in totals.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='householdcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive records are hidden from lists and pickers but still count in totals.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='household.householdmember', verbose_name='Paid by'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='household.householdcategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='household.householdmember', verbose_name='Member'),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='Note'),
        ),
    ]
